/* Auto-generated by scripts/optimize-gallery.mjs — do not edit manually */
export type GalleryImage = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
};

export const galleryImages = [
  {
    "src": "/images/gallery/enforcement-directorate-complaint.webp",
    "alt": "Advocates Neelamegam and Muthukumar filing complaint at Enforcement Directorate Madurai office",
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMAAsAA4BaJbACdADhcmqpTo0sAAD+pYKGAtKe6XGGuFoHmW1BQH/tD8A+7MunFiD4clOO12oehRsc3kNCArZjeFQQfV5KkKzppY46/Jj2C8u1fiXSQAAA",
    "width": 612,
    "height": 580
  },
  {
    "src": "/images/gallery/thanthi-tv-bank-harassment-ruling.webp",
    "alt": "Thanthi TV news on Madras High Court Madurai Bench ruling against bank harassment of borrowers",
    "blurDataURL": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAADwAQCdASoMAAwAA4BaJbACdAEXfKum63AA/pO/f+0Oo0qXhNNF5E577FofIwuv4WpvUUMnE0A6bzOz/RGUqRwIGeBDWqPDx+RzFmJGLbrSgQlTCnWq5CdrD6cAAA==",
    "width": 496,
    "height": 503
  },
  {
    "src": "/images/gallery/news7-tamil-advocate-interview.webp",
    "alt": "Advocate K. Neelamegam interviewed by News 7 Tamil on digital crime and legal accountability",
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAACwAQCdASoMAAcAA4BaJbACdADZlONAAP7MA7X+er/MUOAjMZaBW/T/TOg4vDnZKG8ihYTxLbMpef88yHCP/ELCAAA=",
    "width": 669,
    "height": 398
  },
  {
    "src": "/images/gallery/keelathooval-memorial-petition.webp",
    "alt": "Newspaper coverage of Madurai High Court petition on Keelathooval memorial rights",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAwCdASoMABQAPu1iqU2ppaOiMAgBMB2JaQAAW+9tZdd/+WH50QAA/rQYgF06MYoHyPK4fB8fmxhvFWS6JdojTsNhI5gwfcPvYoAAAAA=",
    "width": 354,
    "height": 586
  },
  {
    "src": "/images/gallery/police-commissioner-fraud-complaint.webp",
    "alt": "Businessman filing fraud complaint at Madurai Police Commissioner office — press coverage",
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADQAQCdASoMAA0AA4BaJZwAAksCgO4QgAD+6xY5N7Mj//vdHhiSMneiWUivOaE4Iwq5A+S3tNbjwgAA",
    "width": 457,
    "height": 500
  },
  {
    "src": "/images/gallery/rbi-2000-notes-legal-opinion.webp",
    "alt": "Newspaper column by Advocate K. Neelamegam on RBI withdrawal of 2000 rupee notes",
    "blurDataURL": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAAAQBACdASoMACEAPuVipk2pJaOiNVgIASAciWcAADgMLNPvdpyCsdYscAD+13BS7sHQa9F2o3+BFtIZkVSvFEtrgSraj3KseD1NefO4peK2ikNAI0+5GZEEezfXw6Uoz/sIR4BjXKA7pIIVEOq18qu+cnn2hkQgAAA=",
    "width": 200,
    "height": 556
  },
  {
    "src": "/images/gallery/mersal-film-legal-complaint.webp",
    "alt": "Advocate K. Neelamegam featured in news on legal complaint regarding Mersal film in Madurai",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAsAA4BaJZQCdAEXYqdU8AD+WwRaFRhq0lTh01dyMdDT5Za8ibwcv0TVy+AA",
    "width": 619,
    "height": 574
  },
  {
    "src": "/images/gallery/matrimonial-legal-press-coverage.webp",
    "alt": "Tamil newspaper legal news coverage featuring Advocate Neelamegam and associates",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAACwAQCdASoMAAkAA4BaJZgAApvpMpgAAP7ojXfzhesV06An1phKJF9HLW2Q91NFP0h/elbgAAA=",
    "width": 465,
    "height": 368
  },
  {
    "src": "/images/gallery/ed-minister-removal-petition.webp",
    "alt": "Advocates filing Enforcement Directorate complaint seeking ministerial post removal",
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoMAAwAA4BaJQBOgCL2x8B8C0IgAP6jPNLKIo0ly077rND0gOWEX0JtEe38xoSXZd3w5t9VwdNjgc+iRBM1JMKfhQ+T4jUl0fiIJSkIr88AAA==",
    "width": 506,
    "height": 485
  },
  {
    "src": "/images/gallery/aadhaav-arjuna-minister-case-news.webp",
    "alt": "Newspaper clipping highlighting Advocate K. Neelamegam in minister removal legal petition",
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAACwAQCdASoMAAcAA4BaJaQAAvqjZjgAAP7fHjm5vPUysasl6oydbT+vhPVAAAAA",
    "width": 800,
    "height": 482
  },
  {
    "src": "/images/gallery/meenakshi-temple-mobile-ban-order.webp",
    "alt": "Newspaper report on High Court order banning mobile phones in Madurai Meenakshi Amman Temple",
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAACQAQCdASoMAAcAA4BaJZQAAlESoYAA4d4aavdM+gQb71vnywaZkNMJ2mM8YsBeiz6pjgAA",
    "width": 800,
    "height": 477
  },
  {
    "src": "/images/gallery/amazon-complaint-police-commissioner.webp",
    "alt": "Advocate K. Neelamegam and colleagues filing complaint at Madurai City Police Commissioner office",
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAA8AA4BaJZQC7AEO4e5aYYAA/uCP/DE1ztgPvjLEupIMhyxQfbBcFdFBs+enP7DsGB0uKv3L4vdWh/R6gAAA",
    "width": 448,
    "height": 565
  }
] as const satisfies readonly GalleryImage[];
