/* Auto-generated by scripts/optimize-hero.mjs — do not edit manually */
export type HeroCarouselSlide = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
  objectPosition: string;
  fit: "cover" | "contain";
};

export const heroCarouselSlides = [
  {
    "src": "/images/hero/lumbini-mobile-banner-court-attire.webp",
    "alt": "Lumbini Law Associates — Advocate K. Neelamegam High Court advocate banner",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoMAAcAA4BaJZwAAsfycmAA/ulR2+qSNhT2VZug/HR3siLds7YJM9BT/AA=",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-mobile-banner-blue-blazer.webp",
    "alt": "Advocate K. Neelamegam — Lumbini Law Associates Madurai legal services banner",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAcAA4BaJZQCdADx9UAAAP7lMQTzV39trx9ozxL9btiCmHdUV+qJ/izy7DPKzUAAAA==",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-mobile-banner-ceremonial.webp",
    "alt": "Advocate K. Neelamegam — experienced dedicated trusted legal advocate banner",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAcAA4BaJZQCw7EURwlQwAD+9YNkFLl8sPei/Zqpy6TblBkuvwqhWehyCTIAAAA=",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  }
] as const satisfies readonly HeroCarouselSlide[];

export const heroCarouselDesktopSlides = [
  {
    "src": "/images/hero/lumbini-poster-court-attire.webp",
    "alt": "Lumbini Law Associates — Advocate K. Neelamegam High Court advocate professional poster",
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAABwAgCdASoMAA8AA4BaJZACdIDZFxR8wmACeiBAAP7w4VPf1f9F8PsLbwBfxU0e8ycLE399WqgvBxS4p/6a71ySTCRsY+U9QN5xZmXUjzXajOIFtb926tuQweGuSvwQAAA=",
    "width": 720,
    "height": 914,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-poster-ceremonial.webp",
    "alt": "Advocate K. Nelamegam — Lumbini Law Associates practice areas and legal services poster",
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAADQAQCdASoMAA8AA4BaJaACdAC3ZRllgAD+8YA33e577x8dPgvwFhAXTdLHku0G1qR6MV5p7bBdCazlvobvjI2qPcKZ0dKh+hT2/F3OKiFkEwNU6eXpUFLY0AA=",
    "width": 720,
    "height": 917,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-poster-outdoor.webp",
    "alt": "Advocate K. Nelamegam — experienced dedicated trusted legal advocate poster",
    "blurDataURL": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQAgCdASoMABAAA4BaJbACdADdRmU+m7eAAP70sPbq+P3QMsL5sdtnusqvuWMSwnpsuUebBYQAztoVkb2ONM0QDA5UvfojMQNvcEfs/0dfQba0FvHzJGvXIFBKesWDhniAFF9AAAA=",
    "width": 720,
    "height": 963,
    "objectPosition": "center center",
    "fit": "contain"
  }
] as const satisfies readonly HeroCarouselSlide[];
