/* Auto-generated by scripts/optimize-hero.mjs — do not edit manually */
export type HeroCarouselSlide = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
  objectPosition: string;
  fit: "cover" | "contain";
};

export const heroCarouselSlides = [
  {
    "src": "/images/hero/lumbini-mobile-banner-court-attire.webp",
    "alt": "Lumbini Law Associates — Advocate K. Neelamegam High Court advocate banner",
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACQAQCdASoMAAcAA4BaJZwAAsfycmAA/ulR2+qSNhT2VZug/HR3siLds7YJM9BT/AA=",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-mobile-banner-blue-blazer.webp",
    "alt": "Advocate K. Neelamegam — Lumbini Law Associates Madurai legal services banner",
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAcAA4BaJZQCdADx9UAAAP7lMQTzV39trx9ozxL9btiCmHdUV+qJ/izy7DPKzUAAAA==",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-mobile-banner-ceremonial.webp",
    "alt": "Advocate K. Neelamegam — experienced dedicated trusted legal advocate banner",
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAcAA4BaJZQCw7EURwlQwAD+9YNkFLl8sPei/Zqpy6TblBkuvwqhWehyCTIAAAA=",
    "width": 960,
    "height": 540,
    "objectPosition": "center center",
    "fit": "contain"
  }
] as const satisfies readonly HeroCarouselSlide[];

export const heroCarouselDesktopSlides = [
  {
    "src": "/images/hero/lumbini-desktop-banner-court-attire.webp",
    "alt": "Lumbini Law Associates — Advocate K. Neelamegam High Court advocate professional poster",
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAQAgCdASoMAA8AA4BaJYgCdAEDfY0d7vEwAP710vizzjISSRpfffjNuu2aFdjgZMrjB/X7qc+7k/e6vB6WOP5sTACQCg5ZODa4jqIAAAA=",
    "width": 720,
    "height": 914,
    "objectPosition": "center center",
    "fit": "contain"
  },
  {
    "src": "/images/hero/lumbini-desktop-banner-blue-blazer.webp",
    "alt": "Advocate K. Neelamegam — Lumbini Law Associates Madurai legal services poster",
    "blurDataURL": "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAAAwAgCdASoMABAAA4BaJaACdADhhdvgD4OIoAD+9euy4X+/B5Hq87fMbQcqwoDDNAsqLgpwgL44TVvmhQ/Q06jZOUr0Vw98i2W6YZb2J8FzDNhPwCSeSIACYFBrhikhoLP4ae1BXn3ejQAA",
    "width": 720,
    "height": 960,
    "objectPosition": "center center",
    "fit": "contain"
  }
] as const satisfies readonly HeroCarouselSlide[];
