/* Auto-generated by scripts/optimize-seo-images.mjs — do not edit manually */
export const advocatePortraitImage = {
  path: "/images/advocate-k-neelamegam-high-court-portrait.webp",
  alt: "Advocate K. Neelamegam — Lumbini Law Associates, High Court Advocate Madurai",
  width: 349,
  height: 449,
} as const;

export const ogShareImage = {
  path: "/images/og-image.webp",
  alt: "Lumbini Law Associates — Advocate K. Neelamegam | High Court Lawyer Madurai",
  width: 1200,
  height: 630,
} as const;
