import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const outDir = path.join(root, "public", "images", "hero");

const MOBILE_MAX_WIDTH = 960;
const DESKTOP_MAX_WIDTH = 720;
const WEBP_QUALITY = 84;
const BLUR_SIZE = 12;

const mobileHeroSources = [
  {
    file: "ChatGPT Image Jun 18, 2026, 08_13_01 AM.png",
    slug: "lumbini-banner-dark",
    alt: "Lumbini Law Associates — Advocate K. Nelamegam professional law firm banner",
    objectPosition: "center center",
    fit: "contain",
  },
  {
    file: "ChatGPT Image Jun 18, 2026, 08_15_08 AM.png",
    slug: "lumbini-banner-blue",
    alt: "Advocate K. Nelamegam — Lumbini Law Associates Madurai legal services banner",
    objectPosition: "center center",
    fit: "contain",
  },
  {
    file: "ChatGPT Image Jun 18, 2026, 08_17_54 AM.png",
    slug: "lumbini-banner-ceremonial",
    alt: "Advocate K. Nelamegam — experienced dedicated trusted legal advocate banner",
    objectPosition: "center center",
    fit: "contain",
  },
];

const desktopHeroSources = [
  {
    file: "ChatGPT Image Jun 18, 2026, 08_28_17 AM.png",
    slug: "lumbini-poster-court-attire",
    alt: "Lumbini Law Associates — Advocate K. Neelamegam High Court advocate professional poster",
    objectPosition: "center center",
    fit: "contain",
  },
  {
    file: "ChatGPT Image Jun 18, 2026, 08_30_22 AM.png",
    slug: "lumbini-poster-ceremonial",
    alt: "Advocate K. Nelamegam — Lumbini Law Associates practice areas and legal services poster",
    objectPosition: "center center",
    fit: "contain",
  },
  {
    file: "ChatGPT Image Jun 18, 2026, 08_32_20 AM.png",
    slug: "lumbini-poster-outdoor",
    alt: "Advocate K. Nelamegam — experienced dedicated trusted legal advocate poster",
    objectPosition: "center center",
    fit: "contain",
  },
];

async function createBlurDataUrl(inputPath) {
  const buffer = await sharp(inputPath)
    .resize(BLUR_SIZE, null, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();

  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function optimizeSlides(sources, maxWidth) {
  const entries = [];

  for (const item of sources) {
    const inputPath = path.join(root, item.file);

    try {
      await fs.access(inputPath);
    } catch {
      console.warn(`Skipping missing file: ${item.file}`);
      continue;
    }

    const outputPath = path.join(outDir, `${item.slug}.webp`);
    const meta = await sharp(inputPath).metadata();
    const width = Math.min(meta.width ?? maxWidth, maxWidth);
    const height = meta.height
      ? Math.round((width / (meta.width ?? 1)) * meta.height)
      : 600;

    await sharp(inputPath)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 4 })
      .toFile(outputPath);

    const optimized = await fs.stat(outputPath);
    const blurDataURL = await createBlurDataUrl(inputPath);

    entries.push({
      src: `/images/hero/${item.slug}.webp`,
      alt: item.alt,
      blurDataURL,
      width,
      height,
      objectPosition: item.objectPosition,
      fit: item.fit,
      bytes: optimized.size,
    });

    console.log(
      `✓ ${item.slug}.webp — ${(optimized.size / 1024).toFixed(1)} KB (from ${item.file})`,
    );
  }

  return entries;
}

function serializeSlides(entries) {
  return JSON.stringify(
    entries.map(({ bytes: _bytes, ...rest }) => rest),
    null,
    2,
  );
}

async function main() {
  await fs.mkdir(outDir, { recursive: true });

  const [mobileEntries, desktopEntries] = await Promise.all([
    optimizeSlides(mobileHeroSources, MOBILE_MAX_WIDTH),
    optimizeSlides(desktopHeroSources, DESKTOP_MAX_WIDTH),
  ]);

  const tsContent = `/* Auto-generated by scripts/optimize-hero.mjs — do not edit manually */
export type HeroCarouselSlide = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
  objectPosition: string;
  fit: "cover" | "contain";
};

export const heroCarouselSlides = ${serializeSlides(mobileEntries)} as const satisfies readonly HeroCarouselSlide[];

export const heroCarouselDesktopSlides = ${serializeSlides(desktopEntries)} as const satisfies readonly HeroCarouselSlide[];
`;

  await fs.writeFile(
    path.join(root, "src", "lib", "hero-carousel-data.ts"),
    tsContent,
    "utf8",
  );

  const totalKb =
    [...mobileEntries, ...desktopEntries].reduce((sum, entry) => sum + entry.bytes, 0) / 1024;
  console.log(
    `\n${mobileEntries.length} mobile + ${desktopEntries.length} desktop hero images — total ${totalKb.toFixed(1)} KB`,
  );
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
