import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const outDir = path.join(root, "public", "images", "gallery");

const GALLERY_MAX_WIDTH = 800;
const WEBP_QUALITY = 82;
const BLUR_SIZE = 12;

const gallerySources = [
  {
    file: "Screenshot 2026-06-17 181810.png",
    slug: "enforcement-directorate-complaint",
    alt: "Advocates Neelamegam and Muthukumar filing complaint at Enforcement Directorate Madurai office",
  },
  {
    file: "Screenshot 2026-06-17 181821.png",
    slug: "thanthi-tv-bank-harassment-ruling",
    alt: "Thanthi TV news on Madras High Court Madurai Bench ruling against bank harassment of borrowers",
  },
  {
    file: "Screenshot 2026-06-17 181931.png",
    slug: "news7-tamil-advocate-interview",
    alt: "Advocate K. Neelamegam interviewed by News 7 Tamil on digital crime and legal accountability",
  },
  {
    file: "Screenshot 2026-06-17 181957.png",
    slug: "keelathooval-memorial-petition",
    alt: "Newspaper coverage of Madurai High Court petition on Keelathooval memorial rights",
  },
  {
    file: "Screenshot 2026-06-17 182016.png",
    slug: "police-commissioner-fraud-complaint",
    alt: "Businessman filing fraud complaint at Madurai Police Commissioner office — press coverage",
  },
  {
    file: "Screenshot 2026-06-17 182042.png",
    slug: "rbi-2000-notes-legal-opinion",
    alt: "Newspaper column by Advocate K. Neelamegam on RBI withdrawal of 2000 rupee notes",
  },
  {
    file: "Screenshot 2026-06-17 182056.png",
    slug: "mersal-film-legal-complaint",
    alt: "Advocate K. Neelamegam featured in news on legal complaint regarding Mersal film in Madurai",
  },
  {
    file: "Screenshot 2026-06-17 182112.png",
    slug: "matrimonial-legal-press-coverage",
    alt: "Tamil newspaper legal news coverage featuring Advocate Neelamegam and associates",
  },
  {
    file: "Screenshot 2026-06-17 182122.png",
    slug: "ed-minister-removal-petition",
    alt: "Advocates filing Enforcement Directorate complaint seeking ministerial post removal",
  },
  {
    file: "Screenshot 2026-06-17 182154.png",
    slug: "aadhaav-arjuna-minister-case-news",
    alt: "Newspaper clipping highlighting Advocate K. Neelamegam in minister removal legal petition",
  },
  {
    file: "Screenshot 2026-06-17 182227.png",
    slug: "meenakshi-temple-mobile-ban-order",
    alt: "Newspaper report on High Court order banning mobile phones in Madurai Meenakshi Amman Temple",
  },
  {
    file: "Screenshot 2026-06-17 182312.png",
    slug: "amazon-complaint-police-commissioner",
    alt: "Advocate K. Neelamegam and colleagues filing complaint at Madurai City Police Commissioner office",
  },
];

async function createBlurDataUrl(inputPath) {
  const buffer = await sharp(inputPath)
    .resize(BLUR_SIZE, null, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();

  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  await fs.mkdir(outDir, { recursive: true });

  const entries = [];

  for (const item of gallerySources) {
    const inputPath = path.join(root, item.file);

    try {
      await fs.access(inputPath);
    } catch {
      console.warn(`Skipping missing file: ${item.file}`);
      continue;
    }

    const outputPath = path.join(outDir, `${item.slug}.webp`);
    const meta = await sharp(inputPath).metadata();

    await sharp(inputPath)
      .rotate()
      .resize({ width: GALLERY_MAX_WIDTH, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 4 })
      .toFile(outputPath);

    const optimized = await fs.stat(outputPath);
    const blurDataURL = await createBlurDataUrl(inputPath);

    entries.push({
      src: `/images/gallery/${item.slug}.webp`,
      alt: item.alt,
      blurDataURL,
      width: Math.min(meta.width ?? GALLERY_MAX_WIDTH, GALLERY_MAX_WIDTH),
      height: meta.height
        ? Math.round(
            (Math.min(meta.width ?? GALLERY_MAX_WIDTH, GALLERY_MAX_WIDTH) /
              (meta.width ?? 1)) *
              meta.height,
          )
        : 600,
      bytes: optimized.size,
    });

    console.log(
      `✓ ${item.slug}.webp — ${(optimized.size / 1024).toFixed(1)} KB (from ${item.file})`,
    );
  }

  const tsContent = `/* Auto-generated by scripts/optimize-gallery.mjs — do not edit manually */
export type GalleryImage = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
};

export const galleryImages = ${JSON.stringify(
    entries.map(({ bytes: _bytes, ...rest }) => rest),
    null,
    2,
  )} as const satisfies readonly GalleryImage[];
`;

  await fs.writeFile(
    path.join(root, "src", "lib", "gallery-data.ts"),
    tsContent,
    "utf8",
  );

  const totalKb = entries.reduce((sum, e) => sum + e.bytes, 0) / 1024;
  console.log(`\n${entries.length} images optimized — total ${totalKb.toFixed(1)} KB`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
