import fs from "fs/promises";
import path from "path";
import { fileURLToPath } from "url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");
const outDir = path.join(root, "public", "images", "hero");

const HERO_MAX_WIDTH = 960;
const WEBP_QUALITY = 84;
const BLUR_SIZE = 12;

const heroSources = [
  {
    file: "Screenshot 2026-06-17 182944.png",
    slug: "advocate-court-attire-portrait",
    alt: "Advocate K. Neelamegam in High Court legal attire with advocate's bands",
    objectPosition: "center 18%",
    fit: "cover",
  },
  {
    file: "Screenshot 2026-06-17 182933.png",
    slug: "legal-team-group-photo",
    alt: "Advocate K. Neelamegam with legal team at Madurai High Court",
    objectPosition: "center 28%",
    fit: "cover",
  },
  {
    file: "Screenshot 2026-06-17 182926.png",
    slug: "advocate-ceremonial-portrait",
    alt: "Advocate K. Neelamegam — professional portrait",
    objectPosition: "center 15%",
    fit: "cover",
  },
  {
    file: "Screenshot 2026-06-17 182917.png",
    slug: "advocate-outdoor-portrait",
    alt: "Advocate K. Neelamegam — trusted High Court lawyer in Madurai",
    objectPosition: "center 20%",
    fit: "cover",
  },
];

async function createBlurDataUrl(inputPath) {
  const buffer = await sharp(inputPath)
    .resize(BLUR_SIZE, null, { fit: "inside" })
    .webp({ quality: 40 })
    .toBuffer();

  return `data:image/webp;base64,${buffer.toString("base64")}`;
}

async function main() {
  await fs.mkdir(outDir, { recursive: true });

  const entries = [];

  for (const item of heroSources) {
    const inputPath = path.join(root, item.file);

    try {
      await fs.access(inputPath);
    } catch {
      console.warn(`Skipping missing file: ${item.file}`);
      continue;
    }

    const outputPath = path.join(outDir, `${item.slug}.webp`);
    const meta = await sharp(inputPath).metadata();
    const width = Math.min(meta.width ?? HERO_MAX_WIDTH, HERO_MAX_WIDTH);
    const height = meta.height
      ? Math.round((width / (meta.width ?? 1)) * meta.height)
      : 1200;

    await sharp(inputPath)
      .rotate()
      .resize({ width, withoutEnlargement: true })
      .webp({ quality: WEBP_QUALITY, effort: 4 })
      .toFile(outputPath);

    const optimized = await fs.stat(outputPath);
    const blurDataURL = await createBlurDataUrl(inputPath);

    entries.push({
      src: `/images/hero/${item.slug}.webp`,
      alt: item.alt,
      blurDataURL,
      width,
      height,
      objectPosition: item.objectPosition,
      fit: item.fit,
      bytes: optimized.size,
    });

    console.log(
      `✓ ${item.slug}.webp — ${(optimized.size / 1024).toFixed(1)} KB (from ${item.file})`,
    );
  }

  const tsContent = `/* Auto-generated by scripts/optimize-hero.mjs — do not edit manually */
export type HeroCarouselSlide = {
  src: string;
  alt: string;
  blurDataURL: string;
  width: number;
  height: number;
  objectPosition: string;
  fit: "cover" | "contain";
};

export const heroCarouselSlides = ${JSON.stringify(
    entries.map(({ bytes: _bytes, ...rest }) => rest),
    null,
    2,
  )} as const satisfies readonly HeroCarouselSlide[];
`;

  await fs.writeFile(
    path.join(root, "src", "lib", "hero-carousel-data.ts"),
    tsContent,
    "utf8",
  );

  const totalKb = entries.reduce((sum, e) => sum + e.bytes, 0) / 1024;
  console.log(`\n${entries.length} hero images optimized — total ${totalKb.toFixed(1)} KB`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
